### ISSUE TITLE
Unable to run without assets

### ISSUE THREAD

**Issue by piyushK52** [HL-hanlin/Ctrl-Adapter#1]
The script given in the readme requires some assets to run (like first_frame, control_frames etc..).. can you guys add a sample assets input so that the script can be run ?

**Comment by HL-hanlin** [comment]
Thanks for catching this! 
We accidentally deleted the sample frames. They've been added back now. 
Let me know if there are any more issues!

**Comment by piyushK52** [comment]
Thanks for the quick response! This seems to be working now
