### ISSUE TITLE
Confused about the small noise latents

### ISSUE THREAD

**Issue by MauroZMJ** [HL-hanlin/Ctrl-Adapter#13]
Thank you for your very nice work! I try to train the adapter based on the SVD model with my own dataset. I'm a little bit confused about the conditional latents 

>https://github.com/HL-hanlin/Ctrl-Adapter/blob/81b77c20a893018b5e4c1790788724e13e53a28a/train.py#L1137-L1145
Here latents have the shape of b c f h w, but the information at the first channel rather than the first frame is used. You mentioned 'adds some noise to the latents constructed from 1st frame'. I don't know whether it is a bug or I misunderstand it.

**Comment by HL-hanlin** [comment]
Hi, 
Really appreciate your feedback! 
Let me look closer into this problem, and I'll reach back to you soon. Thanks again!

**Comment by HL-hanlin** [comment]
Hi there, 
I re-trained the SVD with this problem fixed, and the generated videos look better than our current checkpoint. I'll update the new checkpoint tomorrow. Thanks again for catching this!

**Comment by MauroZMJ** [comment]
It's my pleasure to help improve the ctrl adapter!

**Comment by HL-hanlin** [comment]
Thanks again! 
Please also feel free to let us know if there's any features you would like to be incorporated in our Ctrl-Adapter. We highly value collaborations and contributions from the community!
