### ISSUE TITLE
Can you give more examples, such as sparse frame video control?

### ISSUE THREAD

**Issue by wly-ai-bj** [HL-hanlin/Ctrl-Adapter#4]

**Comment by HL-hanlin** [comment]
sure! I'll update it along with the next task on my todo list :)

**Comment by HL-hanlin** [comment]
sparse control and multi-condition control inference examples updated!

**Comment by HL-hanlin** [comment]
more examples added

**Comment by justinday123** [comment]
Is there reason for using I2VgenXL for sparse control? Also, is there no plan for training code for sparse control?
