### ISSUE TITLE
Can the author provide more examples? such as multiple condition control, node graph control, split graph control and so on

### ISSUE THREAD

**Issue by 2017211801** [HL-hanlin/Ctrl-Adapter#5]
Thank you for your excellent work!

**Comment by HL-hanlin** [comment]
Hi, thanks for your interest in our work! 
- For multi-condition control, I'll update it together with the next commit. 
- For node graph control and split graph control, sorry, I'm not very familiar with their definitions, and we haven't implemented them in our framework yet. Could you give me some pointers where I can learn about them? Thanks!
