### ISSUE TITLE
to do list

### ISSUE THREAD

**Issue by 1585511010** [HL-hanlin/Ctrl-Adapter#8]
hallow，when you will release to do list .I am badly in need of checkpoints and inference code for other models and to do list .could you please give me that.

**Comment by 1585511010** [comment]
thank you!!!!

**Comment by Ledgendary** [comment]
Hey, thanks for the hard work, this is great! excited to give the other models a test!

**Comment by HL-hanlin** [comment]
Hi! 
Thanks for your patience! The training code has been uploaded. Please let me know if you find any issues!
